# Generated by Django 4.1.1 on 2022-10-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_author_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
