# Generated by Django 4.1.1 on 2022-10-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_investigator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigator',
            name='body',
        ),
    ]
